# Generated by Django 5.0.6 on 2024-06-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_persona_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('anio_publicacion', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socio',
            name='libros',
            field=models.ManyToManyField(to='biblioteca_app.libro'),
        ),
        migrations.AddField(
            model_name='socio',
            name='peliculas',
            field=models.ManyToManyField(to='biblioteca_app.pelicula'),
        ),
    ]
