# Generated by Django 5.0.6 on 2024-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_pelicula_libro_stock_socio_libros_socio_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='anio_publicacion',
            field=models.IntegerField(),
        ),
    ]
